--[[
Name: "sv_regeneration.lua".
Product: "Citrus (Server Management)".
--]]

-- PLUGIN.
local PLUGIN = citrus.Plugins.Get("Points")

-- PURCHASE.
local PURCHASE = {}

-- Description.
PURCHASE.Description = "Health is regenerated by a small amount every second"
PURCHASE.Cost = 2
PURCHASE.Name = "Regeneration"

-- On Player Second.
function PURCHASE.OnPlayerSecond(Player)
	local Points = citrus.PlayerVariables.Get(Player, "Points")
	
	-- Check Name.
	if (Points.Purchases[PURCHASE.Name]) then
		Player:SetHealth(math.min(Player:Health() + 5, Player:GetMaxHealth()))
	end
end

-- On Think.
function PURCHASE.OnThink()
	PURCHASE.Cost = (PLUGIN.Configuration["Increment"] * 240) / PLUGIN.Configuration["Interval"]
end

-- Name.
PLUGIN.Purchases[PURCHASE.Name] = PURCHASE